excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://rebeccation.github.io
title: rebeccation
tagline: some stuff that wanted saying
description: reb blogs about stuff
paginate: 10
